import { colors } from '../tokens/colors';
import type { ThemeConfig } from './types';

export const defaultTheme: ThemeConfig = {
  themes: {
    light: {
      id: 'default-light',
      name: 'Default Light',
      colors: {
        background: colors.background.light,
        foreground: colors.foreground.light,
        card: colors.card.light,
        cardForeground: colors.cardForeground.light,
        popover: colors.popover.light,
        popoverForeground: colors.popoverForeground.light,
        primary: colors.primary.light,
        primaryForeground: colors.primaryForeground.light,
        secondary: colors.secondary.light,
        secondaryForeground: colors.secondaryForeground.light,
        muted: colors.muted.light,
        mutedForeground: colors.mutedForeground.light,
        accent: colors.accent.light,
        accentForeground: colors.accentForeground.light,
        destructive: colors.destructive.light,
        destructiveForeground: colors.destructiveForeground.light,
        border: colors.border.light,
        input: colors.input.light,
        ring: colors.ring.light,
      },
      radius: '0.625rem',
    },
    dark: {
      id: 'default-dark',
      name: 'Default Dark',
      colors: {
        background: colors.background.dark,
        foreground: colors.foreground.dark,
        card: colors.card.dark,
        cardForeground: colors.cardForeground.dark,
        popover: colors.popover.dark,
        popoverForeground: colors.popoverForeground.dark,
        primary: colors.primary.dark,
        primaryForeground: colors.primaryForeground.dark,
        secondary: colors.secondary.dark,
        secondaryForeground: colors.secondaryForeground.dark,
        muted: colors.muted.dark,
        mutedForeground: colors.mutedForeground.dark,
        accent: colors.accent.dark,
        accentForeground: colors.accentForeground.dark,
        destructive: colors.destructive.dark,
        destructiveForeground: colors.destructiveForeground.dark,
        border: colors.border.dark,
        input: colors.input.dark,
        ring: colors.ring.dark,
      },
      radius: '0.625rem',
    },
  },
  defaultMode: 'system',
};
